<?php

use \Upg\Library\Callback\Exception\MacValidation;

class Upg_Payments_MnsController extends Mage_Core_Controller_Front_Action
{
    /**
     * @var Upg_Payments_Helper_Data
     */
    protected $helper;

    public function preDispatch()
    {
        parent::preDispatch(); // TODO: Change the autogenerated stub

        $this->helper = Mage::helper('upg_payments');

        return $this;
    }

    /**
     * Handle reserve callbacks
     */
    public function handleAction()
    {
        $config = $this->helper->getConfig();

        $keys = array(
            'merchantID',
            'storeID',
            'orderID',
            'captureID',
            'merchantReference',
            'paymentReference',
            'userID',
            'amount',
            'currency',
            'transactionStatus',
            'orderStatus',
            'additionalData',
            'timestamp',
            'version',
            'mac'
        );

        $data = array();

        foreach ($keys as $K)
        {
            $data[$K] = $this->getRequest()->getParam($K, '');
        }

        $processor = Mage::getModel('upg_payments/message');

        try{

            $handler = new \Upg\Library\Mns\Handler($config, $data, $processor);
            $handler->run();

        }catch (MacValidation $e)
        {
            Mage::logException($e);
            $this->helper->log('HMac Validation failed for MNS message' . $data['orderID'] . ' ' . $e->getMessage());
        }
        catch (Exception $e)
        {
            Mage::logException($e);
            $this->helper->log('Critical error for MNS message' . $data['orderID'] . ' ' . $e->getMessage());
        }

        $this->getResponse()->setHeader('HTTP/1.0','200',true);

        return $this;
    }
}