<?php
/**
 * Intercept various functions for the defult checkout to show iframe
 */
?>
<!-- default one page support -->
<script type="text/javascript">
    UpgMagentoJs.addMethods({
        preparePaymentObserver: function() {
            var UpgMagentoJs = this;
            var _originalPaymentSaveMethod = Payment.prototype.save;
            Payment.prototype.save = function() {
                if(this.currentMethod == 'upg_payments') {
                    var arguments = {
                        fancybox: {
                            is_mobile: UpgMagentoJsIntegration.viewportWidth() <= <?php echo $this->getMaxMobileBrowserWidth() ?>,
                            units: '<?php echo $this->getUnits() ?>',
                            width: '<?php echo $this->getWidth() ?>',
                            height: '<?php echo $this->getHeight() ?>',
                            fit_to_width_desktop: <?php echo json_encode($this->getFitToWidthDesktop()) ?>
                        }
                    };
                    UpgMagentoJsIntegration.setPaymentCallback(_originalPaymentSaveMethod, this);
                    UpgMagentoJsIntegration.getPaymentIframe(arguments);
                } else {
                    return _originalPaymentSaveMethod.apply(this, arguments);
                }
            }
        }
    });

    var UpgMagentoJsIntegration = new UpgMagentoJs();
</script>